<a href="https://colab.research.google.com/github/Raju057/Python-basics/blob/main/Copy_of_Copy_of_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.arange(15).reshape(3,5)

In [ ]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
a.ndim

2

In [ ]:
a.shape

(3, 5)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.size

15

In [ ]:
a.resize(5,3)

In [ ]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
a.ndim

2

Array Creation

*   array from a regular Python list or tuple using the array function. 
*   array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three dimensional
arrays, and so on.


 

In [ ]:
import numpy as np
a = np.array([2,3,4])
a

array([2, 3, 4])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
v=np.array(([2,3],[5,6]))

In [ ]:
v

array([[2, 3],
       [5, 6]])

In [ ]:
v.shape


(2, 2)


*   The function **zeros** creates an array full of zeros
*   function **ones** creates an array full of ones
* function **empty** creates an array whose initial content is random and depends on the state of the memory. 
*  By default, the dtype of the created array is float64, but it can be specified via the key word argument dtype.


In [ ]:
b=np.ones((2,3,2))
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
a=np.zeros((2,3),dtype=np.int16)
a

array([[0, 0, 0],
       [0, 0, 0]], dtype=int16)